### ISSUE TITLE
Error occurred with ticker AL29D: Symbol 'MERV - XMEV - AL29D - 24hs' not found

### ISSUE THREAD

**Issue by ramar72** [ChuchoCoder/chuchobot#1]
Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.ApplicationException: Error occurred with ticker AL29D: Symbol 'MERV - XMEV - AL29D - 24hs' not found. ---> System.Collections.Generic.KeyNotFoundException: Symbol 'MERV - XMEV - AL29D - 24hs' not found.
   en Primary.WinFormsApp.Argentina.GetInstrumentDetail(String symbol) en C:\Users\FedericoBridger\Source\chucho\chuchobot\Primary.WinFormsApp\Shared\Argentina.cs:línea 200
   en Primary.WinFormsApp.TradedInstrumentWithSettlementTerms..ctor(String ticker) en C:\Users\FedericoBridger\Source\chucho\chuchobot\Primary.WinFormsApp\Shared\TradedInstrumentWithSettlementTerms.cs:línea 16
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Primary.WinFormsApp.TradedInstrumentWithSettlementTerms..ctor(String ticker) en C:\Users\FedericoBridger\Source\chucho\chuchobot\Primary.WinFormsApp\Shared\TradedInstrumentWithSettlementTerms.cs:línea 22
   en Primary.WinFormsApp.SettlementTermArbitrationProcessor.Init() en C:\Users\FedericoBridger\Source\chucho\chuchobot\Primary.WinFormsApp\SettlementTerms\SettlementTermArbitrationProcessor.cs:línea 194
   en Primary.WinFormsApp.FrmSettlementTermsAnalyzer.FrmArbitrationBestTrades_Load(Object sender, EventArgs e) en C:\Users\FedericoBridger\Source\chucho\chuchobot\Primary.WinFormsApp\SettlementTerms\FrmSettlementTermsAnalyzer.cs:línea 59
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.ContainerControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ChuchoBot
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///C:/Users/rmsal/OneDrive/A%20PENDRIVE/Inver/ChuchoBot/ChuchoBot2023-10-02/ChuchoBot.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9172.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Primary
    Versión del ensamblado: 0.5.4.0
    Versión Win32: 0.5.4.0
    Código base: file:///C:/Users/rmsal/OneDrive/A%20PENDRIVE/Inver/ChuchoBot/ChuchoBot2023-10-02/Primary.DLL
----------------------------------------
netstandard
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 4.8.9032.0
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Net.Http
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 12.0.0.0
    Versión Win32: 12.0.3.23909
    Código base: file:///C:/Users/rmsal/OneDrive/A%20PENDRIVE/Inver/ChuchoBot/ChuchoBot2023-10-02/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9166.0 built by: NET481REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.9032.0 built by: NET481REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by ChuchoCoder** [comment]
Este issue lo corregí en la release del 2023-Oct-03. Descarga la ultima release y probalo nuevamente. Si sigue sin funcionar avisame.
