### ISSUE TITLE
Aranceles de caucion no se leen de la configuracion

### ISSUE THREAD

**Issue by DelNono** [ChuchoCoder/chuchobot#10]
A pesar de haber colocado los valores de los aranceles de caucion en el archivo de configuracion, el bot no los esta levantando, no es urgente, de momento os pongo a mano al inicio. Ver abajo fragmento en XML.

<setting name="ArancelCaucionColocadora" serializeAs="String">
		<value>1.0</value>
</setting>
<setting name="ArancelCaucionTomadora" serializeAs="String">
		<value>4.0</value>
</setting>

**Comment by ChuchoCoder** [comment]
@ccrosetti Lo que describís es el funcionamiento correcto y por diseño. 

El setting de `Comision` es un setting de Usuario, cuando se cambia este valor en la aplicación se guardan en `%userprofile%\appdata\local\Primary\` o `%userprofile%\Local Settings\Application Data\Primary\`

**Comment by DelNono** [comment]
Gracias Chucho, encontre la carpeta que mencionaste y de esa configuracion esta levantando bien esos paarametros, anula el issue silo consideras conveniente.
